language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - REPO_NAME="cakephp-upload"
    - PLUGIN_NAME=Upload
  matrix:
    - DB=mysql CAKE_VERSION=master
    - DB=mysql CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.4
      env:
        - DB=mysql CAKE_VERSION=master COVERALLS=1
    - php: 5.4
      env:
        - DB=mysql CAKE_VERSION=master PHPCS=1

branches:
  only:
    - upload-s3-behavior

before_install:
  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update

before_script:

  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../upload app/Plugin/Upload
  - chmod -R 777 ../cakephp/app/tmp
  - cp ../upload/Config/app_composer.json app/composer.json
  - cd app && composer install --dev --prefer-source --no-interaction && cd ..
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => '',
      'encoding' => 'utf8'
    );
    }" > ./app/Config/database.php

  - mkdir ./app/Config/Upload && cp ./app/Plugin/Upload/Config/file_storages.ini.sample ./app/Config/Upload/file_storages.ini

script:

  - ./app/Console/cake test Upload AllUpload --stderr

notifications:
  email: false
